version: 1.0.{build}
image: Ubuntu

install:
  - npm ci

build_script:
  - npm run build

test_script:
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
  - npm test || true

artifacts:
  - path: dist
    name: build

deploy_script:
  - export GIT_AUTHOR_NAME="Appveyor"
  - export GIT_AUTHOR_EMAIL="appveyor@ci.com"
  - export GIT_COMMITTER_NAME="Appveyor"
  - export GIT_COMMITTER_EMAIL="appveyor@ci.com"
  - git config --global user.email "appveyor@ci.com"
  - git config --global user.name "Appveyor CI"
  - git remote set-url origin https://$GITHUB_TOKEN@github.com/simplespacej/credit-card-validator.git
  - npm run deploy
